version: "3"
services:
  jupyter-lab:
    build:
      context: ./services/lab
      dockerfile: ${DOCKER_FILE:-Dockerfile}
    volumes:
      - "${NOTEBOOKS_PATH:-./notebooks}:/home/lab/nbs"
    ports:
      - 8888:8888
    stdin_open: true # docker run -i
    tty: true # docker run -t
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"
    restart: unless-stopped
    command: jupyter lab --no-browser --allow-root --port=8888
