version: "3"
services:
  jupyter-lab:
    build:
      context: ./services/lab
    volumes:
      - ./nbs/:/home/lab/nbs/:z
    ports:
      - 8888:8888
    stdin_open: true # docker run -i
    tty: true # docker run -t
    env_file:
      - ./.env
    command: jupyter lab --no-browser --allow-root --port=8888

  nginx:
    build: ./services/nginx
    ports:
      - 1337:80
    depends_on:
      - "jupyter-lab"
